"""add retry config to data_source_rate_limits

Revision ID: 3a75613abb89
Revises: 980d5659e4cd
Create Date: 2026-01-05 00:26:33.573878

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a75613abb89'
down_revision: str | Sequence[str] | None = '980d5659e4cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_rate_limits', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('data_source_rate_limits', sa.Column('backoff_multiplier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source_rate_limits', 'backoff_multiplier')
    op.drop_column('data_source_rate_limits', 'max_retries')
    # ### end Alembic commands ###
