"""add supports_etags to data_source_refresh_policies

Revision ID: 5a94c6334a35
Revises: 8e53bbbd6b84
Create Date: 2026-01-05 00:43:05.547526

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a94c6334a35'
down_revision: str | Sequence[str] | None = '8e53bbbd6b84'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_refresh_policies', sa.Column('supports_etags', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source_refresh_policies', 'supports_etags')
    # ### end Alembic commands ###
