"""add payload_mapping to data_source_capabilities

Revision ID: 980d5659e4cd
Revises: d8a0021645a7
Create Date: 2026-01-05 00:08:52.695139

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '980d5659e4cd'
down_revision: str | Sequence[str] | None = 'd8a0021645a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_capabilities', sa.Column('payload_mapping', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source_capabilities', 'payload_mapping')
    # ### end Alembic commands ###
