"""add endpoint_path to data_source_capabilities

Revision ID: d8a0021645a7
Revises: b92f2865ef96
Create Date: 2026-01-05 00:04:52.004213

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8a0021645a7'
down_revision: str | Sequence[str] | None = 'b92f2865ef96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_capabilities', sa.Column('endpoint_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source_capabilities', 'endpoint_path')
    # ### end Alembic commands ###
